; MEMORY ADDRESSES FOR SCREEN AND COLOUR DATA
SA_SCN$ =       $1000
SA_CLM$ =       $9400

; IRQ VECTOR INSTALLATION LOCATION
VC_IRQ$ =       $0314

; VIC SOUND AND DISPLAY REGISTERS
VICO2F$ =       $900B
VICO3F$ =       $900C
VICSGV$ =       $900E
VICSCL$ =       $900F

; BASIC AND KERNAL ROUTINE ADDRESSES
BASPST$ =       $CB1E
KNLPLT$ =       $FFF0
KNLGET$ =       $FFE4
KNLSNM$ =       $FFBD
KNLSLF$ =       $FFBA
KNLOPN$ =       $FFC0
KNLCLS$ =       $FFC3
KNLCKO$ =       $FFC9
KNLCLC$ =       $FFCC
KNLCHO$ =       $FFD2